# Generated by Django 3.1.3 on 2020-11-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('disc', models.CharField(default='  ', max_length=300)),
                ('prod_date', models.DateField()),
            ],
        ),
    ]
