# Generated by Django 3.1.3 on 2020-11-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(default=' ', max_length=90)),
                ('address', models.CharField(default=' ', max_length=220)),
                ('city', models.CharField(default=' ', max_length=100)),
                ('state', models.CharField(default='  ', max_length=110)),
                ('zip_code', models.CharField(default='  ', max_length=10)),
            ],
        ),
    ]
